db:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: ""
    MYSQL_ALLOW_EMPTY_PASSWORD: yes
  ports:
    - "3306:3306"
  command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
